server:
  port: 30000
  servlet:
    session:
      tracking-modes: COOKIE
spring:
  profiles: dev
  datasource:
    database-name: keyduck
    url : jdbc:mysql://101.101.210.98:3306/keyduck?reconnect=true&useUnicode=true&characterEncoding=utf8
    username: summer
    password: Jh2021^^

  jackson:
    serialization:
      fail-on-empty-beans : false
  jpa:
    show-sql: true
    generate-ddl: true
    database : mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

file :
  upload-dir : ./uploads


