server:
  port: 8080
  servlet:
    session:
      tracking-modes: COOKIE
spring:
  profiles: dev
  datasource:
    database-name: 	jlbf7hrr7t7gi1z2
    url : jdbc:mysql://o93x5an9ii7fl044:o9odhxvnxxekv0k8@nnsgluut5mye50or.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/l6cliyeqenfdryjl?reconnect=true&useUnicode=true&characterEncoding=utf8
    host-name : nnsgluut5mye50or.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
    username: o93x5an9ii7fl044
    password: o9odhxvnxxekv0k8

  jackson:
    serialization:
      fail-on-empty-beans : false
  jpa:
    show-sql: true
    generate-ddl: true
    database : mysql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

file :
  upload-dir : ./uploads


