server:
  port: 30000
  servlet:
    session:
      tracking-modes: COOKIE
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    database-name: r8t815o9w6ulfysd
    url : jdbc:mysql://l6glqt8gsx37y4hs.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/r8t815o9w6ulfysd?reconnect=true&useUnicode=true&characterEncoding=utf8
    username: mvsevbab7tkng5uo
    password: zflcv87gq1w2bgdc
  jackson:
    serialization:
      fail-on-empty-beans : false
  jpa:
    show-sql: true
    generate-ddl: true
    database : mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    jest:
      uri: https:@cypress-925704988.us-east-1.bonsaisearch.net:443
      username: sktiakca3l
      password: s855y1zn3n
file :
  upload-dir : ./uploads

es:
  host: cedar-78838687.us-east-1.bonsaisearch.net
  port: 443
  username: 9cw7dfi4v1
  password: gqwtynvdpz
