server:
  port: 8080
  servlet:
    session:
      tracking-modes: COOKIE
spring:
  profiles: dev
  datasource:
    database-name: heroku_62a3453fd580d8a
    url : jdbc:mysql://b7c287d6c3ef56:d15ece33@us-cdbr-east-04.cleardb.com/heroku_62a3453fd580d8a?reconnect=true?useUnicode=true&characterEncoding=utf8
    host-name : us-cdbr-east-04.cleardb.com
    username: b7c287d6c3ef56
    password: d15ece33

  jackson:
    serialization:
      fail-on-empty-beans : false
  jpa:
    show-sql: true
    generate-ddl: true
    database : mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

file :
  upload-dir : ./uploads


