server:
  port: 8070
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/keyduck?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Keyduck2021^^


  jackson:
    serialization:
      fail-on-empty-beans : false
  jpa:
    show-sql: true
    generate-ddl: true
    database : mysql
    hibernate:
      ddl-auto: none

    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

file :
  upload-dir : ./uploads