server:
  port: 8070

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/keyduck?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Keyduck2021^^
  jackson:
    serialization:
      fail-on-empty-beans : false
  jpa:
    show-sql: true
    generate-ddl: true
    database : mysql
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

file :
  upload-dir : ./uploads

sns:
  kakao:
    url : https://kauth.kakao.com/oauth/authorize
    client_id : d5c1915fd9a1a45bc3a8fa76291045b8
    redirect_uri: http://localhost:8070/v1/KAKAO/kakao_login
    response_type : code
    grant_type : authorization_code
    client_secret : 7AlTUg5Ew2Hb0UvDfemmHVOcTw9I2m9h

es:
  host: localhost
  port: 9200
  username:
  password: