server:
  port: 30000
  servlet:
    session:
      tracking-modes: COOKIE
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    database-name: t863regljymogm0m
    url : jdbc:mysql://exbodcemtop76rnz.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/t863regljymogm0m?reconnect=true&useUnicode=true&characterEncoding=utf8
    username: wvj5te54qifdmhmz
    password: yhitm6m5jwsmzsqz
  jackson:
    serialization:
      fail-on-empty-beans : false
  jpa:
    show-sql: true
    generate-ddl: true
    database : mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    jest:
      uri: https:@cypress-925704988.us-east-1.bonsaisearch.net:443
      username: sktiakca3l
      password: s855y1zn3n
file :
  upload-dir : ./uploads

es:
  host: cypress-925704988.us-east-1.bonsaisearch.net
  port: 443
  username: 7blt98m7u2
  password: zdaj66822u
