server:
  port: 8020
  servlet:
    session:
      tracking-modes: COOKIE
spring:
  profiles:
    active: dev
  datasource:
    database-name: heroku_cdbf458e3f408e0
    url : jdbc:mysql://b838e559b88477:65b3016d@us-cdbr-east-04.cleardb.com/heroku_cdbf458e3f408e0?reconnect=true
    host-name : us-cdbr-east-04.cleardb.com
    username: b838e559b88477
    password: 65b3016d

  jackson:
    serialization:
      fail-on-empty-beans : false
  jpa:
    show-sql: true
    generate-ddl: true
    database : mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

file :
  upload-dir : ./uploads


